#!/bin/sh
#
# Start logging
#

case "$1" in
  start)
	echo -n "Starting logging: "
	start-stop-daemon -S -q -p /var/run/syslog.pid --exec /sbin/syslogd -- -m 0
	start-stop-daemon -S -q -p /var/run/klogd.pid --exec /sbin/klogd
	start-stop-daemon -S -q  -m -p /var/run/logd.pid --exec /sbin/logd
	echo "OK"
	;;
  stop)
	echo -n "Stopping logging: "
	start-stop-daemon -K -q -p /var/run/syslog.pid
	start-stop-daemon -K -q -p /var/run/klogd.pid
	start-stop-daemon -K -q -p /var/run/logd.pid
	echo "OK"
	;;
  restart|reload)
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
