all:
	make -i -f MakefileUnity.mk 
Debug: 
	make -i -f MakefileUnity.mk 

controller:
	$(MAKE) -C ./src/Controller/ engstatcom 

cleancontroller:
	$(MAKE) -C ./src/Controller/ cleancontroller 

clean:
	make -i -f MakefileUnity.mk clean
	
cleanall:
	make -i -f MakefileUnity.mk clean

